### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by heguro** [heguro/nostr-following-list-util#2]
- [ ] Get follower's kind0 events (become Nostr client?)
  - [ ] Followees list
  - [ ] Followees diff
  - [ ] Export with username
  - [ ] See followers and follow back
- [x] English support #1
- [ ] More specific sending status
- [ ] Edit list of relays to send
- [x] Add a relay by url a189eec259f5b932069f87c84200b22450a83cc1
- [ ] Export npubs instead of hexes
- [ ] More importable file type (ex. event, nostr-backup, iris backup)
- [ ] Use latest relays list when importing backup with no relays list
- [ ] Send kind10002 event when updating relays (Partial: 913af15db2db96724603b2e75a534cdf6778070b)
- [ ] Better display of kind10002 events (Currently hidden by default: 5ac89d0bac9bae434ff378748cb9a6033c7aad05)
- [ ] Toggle dark mode
- [x] Toggle language 5ac89d0bac9bae434ff378748cb9a6033c7aad05
- [x] Show NIP-11 relay information 4cab897afebea8432eec68f94fc696e42abb3f83
- [ ] Revisit "Combine selected following lists" feature
  - > The "Merge selected lists" feature of NostrFlu is not at all intuitive, and I don't think anyone uses it, including myself, so I'd like to consider making it better or even removing it.
- [ ] Redesign / Refine UI
  - [ ] Title bar
  - [ ] Custom button style (because iOS Safari's system button is completely not customizable and too thin to press)
  - [ ] UI to open settings
  - [ ] Reasonable UI to access all features more easily
- [ ] Support URL param (mainly for badges)
- [ ] Support nprofile (login, show, copy)
- [ ] Show more events
  - [ ] Text notes
  - [ ] Faves
  - [ ] Bookmarks
- [ ] Refactoring

badges

- [ ] Exclude duplicated badges with same d tag
- [ ] Create badges
- [ ] Award badge to users
  - [ ] by recently replied/faved
  - [ ]
